params:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  total_steps: ev(${trainer.max_epochs} * ${datamodule.len_train_dataset} / ${datamodule.params.batch_size})
  pct_start: 0.1
  max_lr: 0.0004
step: 'step'