name: Transformer

defaults:
  - _self_
  - model: model1
  - scheduler: OneCycleLR
  - optimizer: Adam
  - loss: CrossEntropyLoss
  - trainer: trainer
  - datamodule: datamodule1
  - logger: wandb


general:
  epochs: 1
  batch_size: 4
  max_lr: 0.0006
  logging: true
  device: gpu
  default_dir: ${hydra:run.dir}/