name: Experiment 2

logging: True # if False wandb will not log
id_resume: null # if not none wandb will continue log for this id run

transforms: t2 # File of transfroms config
model: m2 # File of model config
scheduler: s4 # File of scheduler config
optim: o3 # File of optim config

train: # Train dirs
  dir: ../input/hwt-russian-dataset/dataset/dataset/train
  labels: ../input/hwt-russian-dataset/dataset/dataset/train.tsv
test: # Test dirs
  dir: ../input/hwt-russian-dataset/dataset/dataset/test/
  labels: ../input/hwt-russian-dataset/dataset/dataset/test.tsv

epochs: 60
batch: 128 # Если ставить батч 16, то лосс не падает
device: cuda