name: T1
params:

  Grayscale:
    params:
      num_output_channels: 1
    prob: 1

  ColorJitter:
    params:
      brightness: 0
      contrast: [2, 3]
      saturation: 0
      hue: 0
    prob: 0

  GaussianBlur:
    params:
      kernel_size: [3, 3]
    prob: 0
    
  Resize:
    params:
      size: [64, 224]
    prob: 1
  