_target_: pytorch_lightning.loggers.WandbLogger
project: First ViT
log_model: true
name: >
  P_${model.patch_size}
  -H_${model.num_heads}
  -L_${model.num_layers}
  -E_${model.emb_len}
  -D_${model.drop_rate}
  -LR_${scheduler.params.max_lr}
  -Epochs_${general.epochs}
